export const MANUAL_RAG_CONTEXT = [
  "Name: Patrick Araujo.",
  "Primary roles: Backend Software Engineer, API Integration Engineer, Solutions Architect.",
  "Website: https://pklavc.com",
  "About page: https://pklavc.com/about/",
  "Projects page: https://pklavc.com/projects/",
  "Blog page: https://pklavc.com/blog/",
  "GitHub profile: https://github.com/PkLavc",
  "LinkedIn profile: https://www.linkedin.com/in/pklavc/",
  "Contact email: contact@pklavc.com",
  "Core stack: Python, Node.js, SQL, JavaScript, PostgreSQL, REST APIs, AWS, Google Cloud, Zoho, Deluge.",
  "Architecture focus: automation, API integrations, ETL pipelines, backend scalability, system design, integration governance.",
  "Measured impact: 8K-12K daily transactions, ~3 hours/day saved per analyst, ~40% faster processing, ~35-40% faster APIs.",
  // ── Employment history (actual jobs) ──────────────────────────────────────
  "EMPLOYMENT HISTORY (companies Patrick actually worked at as an employee):",
  "Job 1 — Loja do Sapo: e-commerce company. Role: Solutions Architect / Backend & Integration Engineer. Built ERP sync pipelines, API automation workers, and operational reporting infrastructure handling 8K-12K daily transactions.",
  "Job 2 — iCaiu: tech/operations company. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation systems, and reporting dashboards. Reduced processing time ~40% and analyst manual work ~3 hours/day.",
  "Job 3 — WR Auto Pecas: auto parts company. Earlier career; backend automation and internal systems work.",
  // ── Critical disambiguation ───────────────────────────────────────────────
  "IMPORTANT — NEVER confuse certification providers with employers: Google, AWS, Datadog, and Coursera are ONLY certification/training providers. Patrick has NEVER worked at Google, AWS, or Datadog as an employee.",
  "IMPORTANT — PkLavc is Patrick's personal portfolio handle/brand and the domain pklavc.com is his portfolio website, NOT a company he founded or works at.",
  // ── Projects ──────────────────────────────────────────────────────────────
  "Projects (full list): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
  "Lavc Systems: local desktop/web AI platform — multi-agent orchestration (LangGraph), FastAPI backend, React/Vite/TypeScript frontend, Ollama local LLM (qwen2.5-coder:7b), ChromaDB RAG, HybridMemory (SQLite + ChromaDB), Kanban task management, APScheduler, autonomous goals, real-time WebSocket observability. Project page: https://pklavc.com/projects/lavc-systems/",
  "Skyler Assistant: public portfolio AI chatbot running on Cloudflare Workers — manual RAG, provider fallback (Groq → OpenRouter), Web Speech API voice, D1 + KV session memory. Demo: https://pklavc.com/projects/skyler-assistant/demo/ Project page: https://pklavc.com/projects/skyler-assistant/",
  "CodePulse Monorepo: online IDE built as a standalone HTML app with Fastify backend on Render and 85%+ Playwright E2E coverage. Project page: https://pklavc.com/projects/codepulse-monorepo/",
  "Google Auth Worker: OAuth orchestration worker in JavaScript + GitHub Actions for issuing Google tokens and triggering downstream jobs. Project page: https://pklavc.com/projects/google-auth-worker/",
  "Multi-Tenant SaaS Platform: enterprise-grade backend with row-level tenancy, RBAC, BullMQ background jobs. TypeScript + NestJS + PostgreSQL. Project page: https://pklavc.com/projects/multi-tenant-saas-platform/",
  "Cipher Gate Proxy: Zero-Trust proxy with AES-256 encryption, dynamic data masking, and automated PII detection. Python. Project page: https://pklavc.com/projects/cipher-gate-proxy/",
  "Aegis Sentinel: autonomous infrastructure recovery engine with predictive anomaly detection and self-healing. Python. Project page: https://pklavc.com/projects/aegis-sentinel/",
  "Cloud Deployment Showcase: production-ready container orchestration, IaC, and CI/CD. Docker + Nginx + GitHub Actions. Project page: https://pklavc.com/projects/cloud-deployment-showcase/",
  "Event-Driven Integration Service: reliable webhook processing with HMAC security and distributed tracing. NestJS + BullMQ + OpenTelemetry. Project page: https://pklavc.com/projects/event-driven-integration-service/",
  "OS Resource Optimizer: high-performance CPU scheduling and memory allocation engine. C++17. Project page: https://pklavc.com/projects/os-resource-optimizer/",
  "Zoho Integration Worker: syncs Zoho Creator records to Google Sheets as part of the ETL reporting backbone. JavaScript + GitHub Actions + Google Sheets API. Extracts records via API, normalizes mapped fields, publishes structured datasets for downstream analytics. Contributes to ~40% reduction in data processing time. Project page: https://pklavc.com/projects/zoho-integration-worker/",
  "Hablla Integration Worker: event-triggered integration worker connecting Hablla marketing platform to downstream reporting systems. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/hablla-integration-worker/",
  "Zenvia Integration Worker: SMS and messaging automation worker for Zenvia platform. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/zenvia-integration-worker/",
  "SIGE Integration Worker: SIGE ERP synchronization worker. Extracts and normalizes ERP records for reporting pipelines. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/sige-integration-worker/",
  "Omie Integration Worker: Omie ERP integration and data synchronization worker. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/omie-integration-worker/",
  // ── Blog posts ────────────────────────────────────────────────────────────
  "Blog: Patrick writes technical articles on backend engineering, automation, SaaS architecture, and AI systems. Blog listing: https://pklavc.com/blog/",
  "Blog post — Building Lavc Systems: Architecture of a Local Multi-Agent AI Platform (AI Platform Engineering, 14 min): FastAPI backend, React/Vite, Ollama local LLM, LangGraph multi-agent orchestration, ChromaDB RAG, HybridMemory, WebSocket observability. URL: https://pklavc.com/blog/lavc-systems-architecture/",
  "Blog post — Backend Automation Systems: How to Reduce Manual Operations Without Breaking Reliability (Backend Engineering, 9 min): queue workers, auditability, retries, safe failure handling in production. URL: https://pklavc.com/blog/backend-automation-systems/",
  "Blog post — UX Analysis: How the GTA VI Official Website Builds Hype Through Motion and Storytelling (UX Analysis, 7 min): motion design, scroll storytelling, visual hierarchy, microinteractions. URL: https://pklavc.com/blog/gta-vi-website-ux-analysis/",
  "Blog post — Multi-Tenant SaaS Architecture: Patterns for Secure and Scalable APIs (SaaS Architecture, 10 min): tenant isolation, RBAC, queue workers, scalable API design. URL: https://pklavc.com/blog/multi-tenant-saas-architecture/",
  "Blog post — Event-Driven API Integrations: Designing for Retries, Idempotency, and Traceability (API Design, 8 min): idempotency, retries, traceability, safe webhook processing. URL: https://pklavc.com/blog/event-driven-api-integrations/",
  "Blog post — OAuth Token Management in Backend Workers: Secure Credential Flow for API Integrations (Security, 7 min): OAuth token acquisition, distribution, refresh in Node.js workers. URL: https://pklavc.com/blog/oauth-token-management/",
  "Blog post — Zero-Trust API Proxy Design: AES-256 Encryption and PII Detection in Python (Security Engineering, 9 min): AES-256 encryption, dynamic field masking, automated PII detection. URL: https://pklavc.com/blog/api-proxy-security-design/",
  "Blog post — ETL Pipelines in API Integration Workers: Data Extraction, Normalization, and Sync (Data Engineering, 8 min): ETL pipeline design in Node.js, CRM/ERP API extraction, payload normalization. URL: https://pklavc.com/blog/integration-worker-etl-pipelines/",
  "Blog post — Monorepo Architecture for Backend APIs: CI Workflows and Code Execution at Scale (Backend Architecture, 9 min): Node.js monorepo structure, code execution services, CI automation, QA coverage. URL: https://pklavc.com/blog/monorepo-backend-architecture/",
  "Blog post — Infrastructure Anomaly Detection and Self-Healing Backends in Python (Infrastructure, 10 min): predictive anomaly detection, autonomous recovery workflows in Python. URL: https://pklavc.com/blog/infrastructure-anomaly-detection/",
  "Blog post — Cloud Deployment Patterns: Container Orchestration, CI/CD, and Infrastructure as Code (DevOps, 8 min): Docker container orchestration, CI/CD pipelines, IaC for scalable backends. URL: https://pklavc.com/blog/cloud-deployment-patterns/",
  "Blog post — Web Performance for Immersive Marketing Sites: How to Keep Heavy Experiences Fluid (Web Performance, 7 min): lazy loading, image/video optimization, asset compression, visual effects trade-offs. URL: https://pklavc.com/blog/web-performance-immersive-marketing/",
  "Blog post — Data Engineering for Game Marketing Hype: Engagement Signals in AAA Launches (Data Engineering, 8 min): traffic observability, audience segmentation, hype forecasting through analytics pipelines. URL: https://pklavc.com/blog/aaa-game-launch-data-engineering/",
  "Blog post — AAA Game Leaks: Security Engineering, Asset Protection, and Social Engineering Risks (Security, 9 min): attack surfaces in content pipelines, digital asset protection, social engineering risks. URL: https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
  "Blog post — Global Launch Systems Architecture: What Happens When Millions Hit a Site at Once (Systems Architecture, 11 min): CDN strategy, cache topology, autoscaling, failure isolation for massive traffic. URL: https://pklavc.com/blog/global-launch-systems-architecture/",
  "Blog post — Automating AAA Launch Tracking: Bots, Site Change Monitoring, and Hype Intelligence (Automation, 8 min): monitoring AAA game launches, detecting site updates, hype tracking pipelines. URL: https://pklavc.com/blog/game-launch-monitoring-automation/",
  // ── Credentials ───────────────────────────────────────────────────────────
  "Current public credential: Member of GitHub Developer Program.",
  "Education and credentials context is available on the About page.",
  "Certifications (training only, NOT employment): Google Cybersecurity Professional Certificate, Google Data Analytics Professional Certificate, Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner, Datadog Foundation.",
  "Full certifications list: Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
];

export const MANUAL_RAG_SECTIONS: Array<{ key: string; keywords: string[]; content: string[]; contentPt?: string[]; contentEs?: string[] }> = [
  {
    key: "intro",
    keywords: [
      // PT
      "quem é o patrick", "quem e o patrick", "quem é você", "quem e voce", "quem é vc", "quem é ele",
      "me fale do patrick", "me fale de você", "me fale sobre o patrick", "fale do patrick", "fale sobre o patrick",
      "me apresenta", "me apresente", "se apresenta", "se apresente",
      "o que você faz", "o que voce faz", "qual é o patrick", "quem te criou", "quem criou você",
      "sobre o patrick", "sobre patrick", "patrick araujo", "pklavc",
      "desenvolvedor", "engenheiro de software",
      // EN
      "who is patrick", "who are you", "tell me about patrick", "about patrick",
      "introduce yourself", "who built you", "who created you", "who made you",
      "who is the developer", "who is the engineer", "who is behind",
      "what do you do", "what does patrick do", "describe patrick",
      // ES
      "quién es patrick", "quién eres", "háblame de patrick", "háblame sobre patrick",
      "preséntate", "quién te creó",
    ],
    content: [
      "Patrick Araujo is a backend and integration-focused software engineer.",
      "He works on automation systems, API integrations, ETL/data pipelines, and scalable backend architecture.",
      "Portfolio about page: https://pklavc.com/about/",
    ],
    contentPt: [
      "Patrick Araujo é um engenheiro de software com foco em backend e integrações.",
      "Trabalha com sistemas de automação, integrações de API, pipelines ETL e arquitetura de backend escalável.",
      "Página sobre: https://pklavc.com/about/",
    ],
    contentEs: [
      "Patrick Araujo es un ingeniero de software especializado en backend e integraciones.",
      "Trabaja en sistemas de automatización, integraciones de API, pipelines ETL y arquitectura de backend escalable.",
      "Página de presentación: https://pklavc.com/about/",
    ],
  },
  {
    key: "experience",
    keywords: [
      // PT
      "trabalho", "trabalhos", "emprego", "empregos", "empresa", "empresas",
      "onde trabalhou", "onde trabalha", "onde já trabalhou", "onde atuou", "onde atua",
      "carreira", "histórico profissional", "historico profissional", "experiência profissional", "experiencia profissional",
      "cargo", "cargos", "função", "funcao", "atuação", "atuacao",
      "histórico", "historico", "trajetória", "trajetoria",
      "clientes", "contratante", "contratantes",
      // EN
      "experience", "work history", "work experience", "career", "employment",
      "where did you work", "where have you worked", "where does patrick work",
      "job history", "jobs", "roles", "positions", "companies worked",
      "professional background", "professional history",
      // ES
      "experiencia laboral", "experiencia profesional", "historial laboral",
      "dónde trabajó", "empresa donde trabajó", "trayectoria", "carrera profesional",
    ],
    content: [
      "Patrick's employment history (actual companies he worked at as an employee):",
      "1. Loja do Sapo — e-commerce company. Role: Solutions Architect / Backend & Integration Engineer. Built ERP synchronization pipelines, API automation workers, and reporting infrastructure handling 8K-12K daily transactions.",
      "2. iCaiu — tech/operations company. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation, and reporting dashboards. Reduced processing time ~40% and saved ~3 hours/day per analyst.",
      "3. WR Auto Pecas — auto parts company. Earlier career. Backend automation and internal systems work.",
      "CRITICAL NOTE: Google, AWS, and Datadog are ONLY certification/training providers — they are NOT employers. Patrick never worked at Google, AWS, or Datadog.",
      "CRITICAL NOTE: PkLavc / pklavc.com is Patrick's personal portfolio brand, not a company.",
      "Full career and experience details: https://pklavc.com/about/",
    ],
    contentPt: [
      "Histórico de empregos do Patrick (empresas onde trabalhou de fato como funcionário):",
      "1. Loja do Sapo — empresa de e-commerce. Cargo: Solutions Architect / Backend & Integration Engineer. Construiu pipelines de sincronização de ERP, workers de automação de API e infraestrutura de relatórios com 8 a 12 mil transações diárias.",
      "2. iCaiu — empresa de tecnologia/operações. Cargo: Systems Integration Architect. Projetou workers de automação, pipelines ETL, sistemas de agregação de dados e dashboards. Reduziu tempo de processamento ~40% e economizou ~3h/dia por analista.",
      "3. WR Auto Peças — empresa de autopeças. Início de carreira. Automação de backend e sistemas internos.",
      "NOTA: Google, AWS e Datadog são APENAS provedores de certificação/treinamento — NÃO são empregadores.",
      "NOTA: PkLavc / pklavc.com é a marca pessoal de portfólio do Patrick, não uma empresa.",
      "Detalhes completos da carreira: https://pklavc.com/about/",
    ],
    contentEs: [
      "Historial de empleo de Patrick (empresas donde trabajó como empleado):",
      "1. Loja do Sapo — empresa de e-commerce. Cargo: Solutions Architect / Backend & Integration Engineer. Construyó pipelines de sincronización ERP, workers de automatización de API e infraestructura de reportes con 8 a 12 mil transacciones diarias.",
      "2. iCaiu — empresa de tecnología/operaciones. Cargo: Systems Integration Architect. Diseñó workers de automatización, pipelines ETL, sistemas de agregación de datos y dashboards. Redujo el tiempo de procesamiento ~40% y ahorró ~3h/día por analista.",
      "3. WR Auto Peças — empresa de autopartes. Inicio de carrera. Automatización de backend y sistemas internos.",
      "NOTA: Google, AWS y Datadog son SOLO proveedores de certificación/entrenamiento — NO son empleadores.",
      "NOTA: PkLavc / pklavc.com es la marca personal de portafolio de Patrick, no una empresa.",
      "Detalles completos de carrera: https://pklavc.com/about/",
    ],
  },
  {
    key: "projects",
    keywords: [
      // PT
      "projeto", "projetos", "portfólio", "portfolio",
      "o que construiu", "o que fez", "o que criou", "o que desenvolveu",
      "criou", "desenvolveu", "construiu", "fez",
      "sistema", "sistemas", "aplicação", "aplicacoes", "aplicacoes",
      "lista de projetos", "quais projetos", "quais são os projetos",
      "repositório", "repositorios", "repos",
      // EN
      "project", "projects", "what did you build", "what has patrick built",
      "what did patrick make", "what did patrick create",
      "built", "made", "created", "developed",
      "portfolio projects", "list of projects", "what projects",
      "applications", "apps", "repositories",
      // ES
      "proyecto", "proyectos", "portafolio",
      "qué construyó", "qué creó", "qué desarrolló",
    ],
    content: [
      "Patrick's projects (full list): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
      "Lavc Systems — local multi-agent AI platform (LangGraph, FastAPI, Ollama, ChromaDB): https://pklavc.com/projects/lavc-systems/",
      "Skyler Assistant — portfolio AI chatbot (Cloudflare Workers): https://pklavc.com/projects/skyler-assistant/",
      "CodePulse Monorepo — online IDE: https://pklavc.com/projects/codepulse-monorepo/",
      "Multi-Tenant SaaS Platform: https://pklavc.com/projects/multi-tenant-saas-platform/",
      "Cipher Gate Proxy: https://pklavc.com/projects/cipher-gate-proxy/",
      "Aegis Sentinel: https://pklavc.com/projects/aegis-sentinel/",
      "Cloud Deployment Showcase: https://pklavc.com/projects/cloud-deployment-showcase/",
      "Event-Driven Integration Service: https://pklavc.com/projects/event-driven-integration-service/",
      "OS Resource Optimizer: https://pklavc.com/projects/os-resource-optimizer/",
      "Google Auth Worker: https://pklavc.com/projects/google-auth-worker/",
      "Zoho Integration Worker: https://pklavc.com/projects/zoho-integration-worker/",
      "Hablla Integration Worker: https://pklavc.com/projects/hablla-integration-worker/",
      "Zenvia Integration Worker: https://pklavc.com/projects/zenvia-integration-worker/",
      "SIGE Integration Worker: https://pklavc.com/projects/sige-integration-worker/",
      "Omie Integration Worker: https://pklavc.com/projects/omie-integration-worker/",
      "All projects: https://pklavc.com/projects/",
      "GitHub: https://github.com/PkLavc",
    ],
    contentPt: [
      "Projetos do Patrick (lista completa): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
      "Lavc Systems — plataforma de IA multi-agente local (LangGraph, FastAPI, Ollama, ChromaDB): https://pklavc.com/projects/lavc-systems/",
      "Skyler Assistant — chatbot de portfólio com IA (Cloudflare Workers): https://pklavc.com/projects/skyler-assistant/",
      "CodePulse Monorepo — IDE online: https://pklavc.com/projects/codepulse-monorepo/",
      "Multi-Tenant SaaS Platform: https://pklavc.com/projects/multi-tenant-saas-platform/",
      "Cipher Gate Proxy: https://pklavc.com/projects/cipher-gate-proxy/",
      "Aegis Sentinel: https://pklavc.com/projects/aegis-sentinel/",
      "Cloud Deployment Showcase: https://pklavc.com/projects/cloud-deployment-showcase/",
      "Event-Driven Integration Service: https://pklavc.com/projects/event-driven-integration-service/",
      "OS Resource Optimizer: https://pklavc.com/projects/os-resource-optimizer/",
      "Google Auth Worker: https://pklavc.com/projects/google-auth-worker/",
      "Zoho Integration Worker: https://pklavc.com/projects/zoho-integration-worker/",
      "Hablla Integration Worker: https://pklavc.com/projects/hablla-integration-worker/",
      "Zenvia Integration Worker: https://pklavc.com/projects/zenvia-integration-worker/",
      "SIGE Integration Worker: https://pklavc.com/projects/sige-integration-worker/",
      "Omie Integration Worker: https://pklavc.com/projects/omie-integration-worker/",
      "Todos os projetos: https://pklavc.com/projects/",
      "GitHub: https://github.com/PkLavc",
    ],
    contentEs: [
      "Proyectos de Patrick (lista completa): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
      "Lavc Systems — plataforma de IA multi-agente local (LangGraph, FastAPI, Ollama, ChromaDB): https://pklavc.com/projects/lavc-systems/",
      "Skyler Assistant — chatbot de portafolio con IA (Cloudflare Workers): https://pklavc.com/projects/skyler-assistant/",
      "CodePulse Monorepo — IDE online: https://pklavc.com/projects/codepulse-monorepo/",
      "Multi-Tenant SaaS Platform: https://pklavc.com/projects/multi-tenant-saas-platform/",
      "Cipher Gate Proxy: https://pklavc.com/projects/cipher-gate-proxy/",
      "Aegis Sentinel: https://pklavc.com/projects/aegis-sentinel/",
      "Cloud Deployment Showcase: https://pklavc.com/projects/cloud-deployment-showcase/",
      "Event-Driven Integration Service: https://pklavc.com/projects/event-driven-integration-service/",
      "OS Resource Optimizer: https://pklavc.com/projects/os-resource-optimizer/",
      "Google Auth Worker: https://pklavc.com/projects/google-auth-worker/",
      "Zoho Integration Worker: https://pklavc.com/projects/zoho-integration-worker/",
      "Hablla Integration Worker: https://pklavc.com/projects/hablla-integration-worker/",
      "Zenvia Integration Worker: https://pklavc.com/projects/zenvia-integration-worker/",
      "SIGE Integration Worker: https://pklavc.com/projects/sige-integration-worker/",
      "Omie Integration Worker: https://pklavc.com/projects/omie-integration-worker/",
      "Todos los proyectos: https://pklavc.com/projects/",
      "GitHub: https://github.com/PkLavc",
    ],
  },
  {
    key: "blog",
    keywords: [
      // PT
      "blog", "publicação", "publicações", "publicacao", "publicacoes",
      "artigo", "artigos", "post", "posts",
      "escreveu", "escrito", "escrita", "conteúdo", "conteudo",
      "o que escreveu", "o que publicou", "o que tem no blog",
      "leitura", "leituras", "texto", "textos",
      // EN
      "article", "articles", "writing", "wrote", "written",
      "what did patrick write", "what has patrick written",
      "blog posts", "content", "reads",
      // ES
      "artículo", "artículos", "publicación", "publicaciones",
      "escribió", "contenido",
    ],
    content: [
      "Patrick's blog covers backend engineering, automation, SaaS architecture, and AI systems. Blog listing: https://pklavc.com/blog/",
      "Building Lavc Systems (AI Platform, 14 min): https://pklavc.com/blog/lavc-systems-architecture/",
      "Backend Automation Systems (9 min): https://pklavc.com/blog/backend-automation-systems/",
      "UX Analysis: GTA VI Website (7 min): https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "Multi-Tenant SaaS Architecture (10 min): https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "Event-Driven API Integrations (8 min): https://pklavc.com/blog/event-driven-api-integrations/",
      "OAuth Token Management (7 min): https://pklavc.com/blog/oauth-token-management/",
      "Zero-Trust API Proxy Design (9 min): https://pklavc.com/blog/api-proxy-security-design/",
      "ETL Pipelines in Integration Workers (8 min): https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "Monorepo Architecture for Backend APIs (9 min): https://pklavc.com/blog/monorepo-backend-architecture/",
      "Infrastructure Anomaly Detection (10 min): https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "Cloud Deployment Patterns (8 min): https://pklavc.com/blog/cloud-deployment-patterns/",
      "Web Performance for Immersive Marketing Sites (7 min): https://pklavc.com/blog/web-performance-immersive-marketing/",
      "Data Engineering for Game Marketing Hype (8 min): https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "AAA Game Leaks: Security Engineering (9 min): https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "Global Launch Systems Architecture (11 min): https://pklavc.com/blog/global-launch-systems-architecture/",
      "Automating AAA Launch Tracking (8 min): https://pklavc.com/blog/game-launch-monitoring-automation/",
    ],
    contentPt: [
      "Blog do Patrick sobre engenharia de backend, automação, arquitetura de sistemas e IA. Listagem: https://pklavc.com/blog/",
      "Building Lavc Systems — plataforma de IA multi-agente (14 min): https://pklavc.com/blog/lavc-systems-architecture/",
      "Backend Automation Systems — redução de operações manuais (9 min): https://pklavc.com/blog/backend-automation-systems/",
      "Análise UX: Site oficial do GTA VI (7 min): https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "Arquitetura Multi-Tenant SaaS (10 min): https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "Integrações de API orientadas a eventos (8 min): https://pklavc.com/blog/event-driven-api-integrations/",
      "Gestão de tokens OAuth em workers (7 min): https://pklavc.com/blog/oauth-token-management/",
      "Proxy API Zero-Trust: AES-256 e detecção de PII (9 min): https://pklavc.com/blog/api-proxy-security-design/",
      "Pipelines ETL em workers de integração (8 min): https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "Arquitetura monorepo para APIs backend (9 min): https://pklavc.com/blog/monorepo-backend-architecture/",
      "Detecção de anomalias e backends auto-corretivos (10 min): https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "Padrões de deploy em cloud (8 min): https://pklavc.com/blog/cloud-deployment-patterns/",
      "Performance web para sites de marketing imersivo (7 min): https://pklavc.com/blog/web-performance-immersive-marketing/",
      "Engenharia de dados para lançamentos AAA (8 min): https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "Vazamentos de jogos AAA: segurança e engenharia social (9 min): https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "Arquitetura de sistemas para lançamentos globais (11 min): https://pklavc.com/blog/global-launch-systems-architecture/",
      "Automatizando rastreamento de lançamentos AAA (8 min): https://pklavc.com/blog/game-launch-monitoring-automation/",
    ],
    contentEs: [
      "Blog de Patrick sobre ingeniería de backend, automatización, arquitectura de sistemas e IA. Listado: https://pklavc.com/blog/",
      "Building Lavc Systems — plataforma de IA multi-agente (14 min): https://pklavc.com/blog/lavc-systems-architecture/",
      "Backend Automation Systems — reducción de operaciones manuales (9 min): https://pklavc.com/blog/backend-automation-systems/",
      "Análisis UX: Sitio oficial de GTA VI (7 min): https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "Arquitectura Multi-Tenant SaaS (10 min): https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "Integraciones de API orientadas a eventos (8 min): https://pklavc.com/blog/event-driven-api-integrations/",
      "Gestión de tokens OAuth en workers (7 min): https://pklavc.com/blog/oauth-token-management/",
      "Proxy API Zero-Trust: AES-256 y detección de PII (9 min): https://pklavc.com/blog/api-proxy-security-design/",
      "Pipelines ETL en workers de integración (8 min): https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "Arquitectura monorepo para APIs backend (9 min): https://pklavc.com/blog/monorepo-backend-architecture/",
      "Detección de anomalías e infraestructura auto-correctiva (10 min): https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "Patrones de despliegue en la nube (8 min): https://pklavc.com/blog/cloud-deployment-patterns/",
      "Rendimiento web para sitios de marketing inmersivo (7 min): https://pklavc.com/blog/web-performance-immersive-marketing/",
      "Ingeniería de datos para lanzamientos AAA (8 min): https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "Filtraciones de juegos AAA: ingeniería de seguridad (9 min): https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "Arquitectura de sistemas para lanzamientos globales (11 min): https://pklavc.com/blog/global-launch-systems-architecture/",
      "Automatizando el seguimiento de lanzamientos AAA (8 min): https://pklavc.com/blog/game-launch-monitoring-automation/",
    ],
  },
  {
    key: "contact",
    keywords: [
      // PT
      "contato", "como entrar em contato", "como falar", "como contratar", "como te contratar",
      "email", "e-mail", "linkedin", "mensagem", "mandar mensagem",
      "redes sociais", "redes", "mídia", "midia",
      "como chamar", "como alcancar", "como alcançar",
      "disponivel", "disponível", "disponibilidade",
      // EN
      "contact", "how to contact", "how to hire", "hire patrick",
      "reach out", "get in touch", "send a message",
      "social media", "social links", "github",
      "available for", "availability",
      // ES
      "contacto", "cómo contactar", "contratar", "correo", "mensaje",
      "redes sociales", "disponible",
    ],
    content: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portfolio: https://pklavc.com",
    ],
    contentPt: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portfólio: https://pklavc.com",
    ],
    contentEs: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portafolio: https://pklavc.com",
    ],
  },
  {
    key: "certificates",
    keywords: [
      // PT
      "certificado", "certificados", "certificação", "certificações", "certificacao", "certificacoes",
      "curso", "cursos", "o que estudou", "o que fez de curso", "cursos que fez",
      "educação", "educacao", "formação", "formacao",
      "credencial", "credenciais", "treinamento", "treinamentos",
      "aprendizado", "qualificação", "qualificacoes", "qualificações",
      "o que estudou", "estudo", "estudos",
      // EN
      "certificate", "certificates", "certification", "certifications",
      "course", "courses", "education", "training",
      "credential", "credentials", "learning", "qualification", "qualifications",
      "what did patrick study", "what has patrick studied",
      // ES
      "certificado", "certificados", "certificación", "certificaciones",
      "curso", "cursos", "educación", "formación", "entrenamiento",
    ],
    content: [
      "Publicly highlighted credential: Member of GitHub Developer Program.",
      "These are CERTIFICATIONS (training), NOT employment. Certification providers include Google, AWS, and Datadog — Patrick never worked at these companies.",
      "Key certifications: Google Cybersecurity Professional Certificate, Google Data Analytics Professional Certificate, Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner, Datadog Foundation.",
      "Full certifications list: Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
      "Education details: https://pklavc.com/about/",
    ],
    contentPt: [
      "Credencial pública: Membro do GitHub Developer Program.",
      "São CERTIFICAÇÕES (treinamento), NÃO empregos. Google, AWS e Datadog são provedores de certificação — Patrick nunca trabalhou nessas empresas.",
      "Principais certificações: Google Cybersecurity Professional Certificate, Google Data Analytics Professional Certificate, Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner, Datadog Foundation.",
      "Lista completa: Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
      "Detalhes de educação: https://pklavc.com/about/",
    ],
    contentEs: [
      "Credencial pública: Miembro del GitHub Developer Program.",
      "Son CERTIFICACIONES (entrenamiento), NO empleos. Google, AWS y Datadog son proveedores de certificación — Patrick nunca trabajó en esas empresas.",
      "Principales certificaciones: Google Cybersecurity Professional Certificate, Google Data Analytics Professional Certificate, Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner, Datadog Foundation.",
      "Lista completa disponible en: https://pklavc.com/about/",
    ],
  },
];