export const MANUAL_RAG_CONTEXT = [
  "Name: Patrick Araujo.",
  "Primary roles: Backend Software Engineer, API Integration Engineer, Solutions Architect.",
  "Website: https://pklavc.com",
  "About page: https://pklavc.com/about/",
  "Projects page: https://pklavc.com/projects/",
  "Blog page: https://pklavc.com/blog/",
  "GitHub profile: https://github.com/PkLavc",
  "LinkedIn profile: https://www.linkedin.com/in/pklavc/",
  "Contact email: contact@pklavc.com",
  "Core stack: Python, Node.js, SQL, JavaScript, PostgreSQL, REST APIs, AWS, Google Cloud, Zoho, Deluge.",
  "Architecture focus: automation, API integrations, ETL pipelines, backend scalability, system design, integration governance.",
  "Measured impact: variable-volume operational systems, ~3 hours/day saved per analyst, ~40% faster processing, ~35-40% faster APIs.",
  // ── Employment history (actual jobs) ──────────────────────────────────────
  "EMPLOYMENT HISTORY (companies Patrick actually worked at as an employee):",
  "Job 1 — Loja do Sapo: Apple technical assistance. Role: Solutions Architect / Backend & Integration Engineer. Built ERP sync pipelines, API automation workers, and operational reporting infrastructure for variable-volume operational workflows.",
  "Job 2 — iCaiu: Apple technical assistance. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation systems, and reporting dashboards. Reduced processing time ~40% and analyst manual work ~3 hours/day.",
  "Job 3 — WR Auto Pecas: auto parts company. Earlier career; backend automation and internal systems work.",
  // ── Critical disambiguation ───────────────────────────────────────────────
  "IMPORTANT — NEVER confuse certification providers with employers: Google, AWS, Datadog, and Coursera are ONLY certification/training providers. Patrick has NEVER worked at Google, AWS, or Datadog as an employee.",
  "IMPORTANT — PkLavc is Patrick's personal portfolio handle/brand and the domain pklavc.com is his portfolio website, NOT a company he founded or works at.",
  // ── Projects ──────────────────────────────────────────────────────────────
  "Projects (full list): Lavc Systems, Skyler Assistant, Raw API Ingestion Pipeline, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
  "Lavc Systems: local desktop/web AI platform — multi-agent orchestration (LangGraph), FastAPI backend, React/Vite/TypeScript frontend, Ollama local LLM (qwen2.5-coder:7b), ChromaDB RAG, HybridMemory (SQLite + ChromaDB), Kanban task management, APScheduler, autonomous goals, real-time WebSocket observability. Project page: https://pklavc.com/projects/lavc-systems/",
  "Skyler Assistant: public portfolio AI chatbot running on Cloudflare Workers — manual RAG, provider fallback (Groq → OpenRouter), Web Speech API voice, D1 + KV session memory. Assistant: https://pklavc.com/skyler-assistant/ Project page: https://pklavc.com/projects/skyler-assistant/",
  "Raw API Ingestion Pipeline: Node.js 20 raw API ingestion pipeline scheduled by GitHub Actions. Collects Hablla, Zoho Creator, Zenvia Voice, and SIGE ERP payloads into Supabase/PostgreSQL raw_* SQL tables with idempotent external IDs, sanitized logs, workflow_dispatch replay, and downstream SQL/BI modeling separation. Project page: https://pklavc.com/projects/raw-api-ingestion-pipeline/",
  "CodePulse Monorepo: online IDE built as a standalone HTML app with Fastify backend on Render and 85%+ Playwright E2E coverage. Project page: https://pklavc.com/projects/codepulse-monorepo/",
  "Google Auth Worker: OAuth orchestration worker in JavaScript + GitHub Actions for issuing Google tokens and triggering downstream jobs. Project page: https://pklavc.com/projects/google-auth-worker/",
  "Multi-Tenant SaaS Platform: enterprise-grade backend with row-level tenancy, RBAC, BullMQ background jobs. TypeScript + NestJS + PostgreSQL. Project page: https://pklavc.com/projects/multi-tenant-saas-platform/",
  "Cipher Gate Proxy: Zero-Trust proxy with AES-256 encryption, dynamic data masking, and automated PII detection. Python. Project page: https://pklavc.com/projects/cipher-gate-proxy/",
  "Aegis Sentinel: autonomous infrastructure recovery engine with predictive anomaly detection and self-healing. Python. Project page: https://pklavc.com/projects/aegis-sentinel/",
  "Cloud Deployment Showcase: production-ready container orchestration, IaC, and CI/CD. Docker + Nginx + GitHub Actions. Project page: https://pklavc.com/projects/cloud-deployment-showcase/",
  "Event-Driven Integration Service: reliable webhook processing with HMAC security and distributed tracing. NestJS + BullMQ + OpenTelemetry. Project page: https://pklavc.com/projects/event-driven-integration-service/",
  "OS Resource Optimizer: high-performance CPU scheduling and memory allocation engine. C++17. Project page: https://pklavc.com/projects/os-resource-optimizer/",
  "Zoho Integration Worker: syncs Zoho Creator records to Google Sheets as part of the ETL reporting backbone. JavaScript + GitHub Actions + Google Sheets API. Extracts records via API, normalizes mapped fields, publishes structured datasets for downstream analytics. Contributes to ~40% reduction in data processing time. Project page: https://pklavc.com/projects/zoho-integration-worker/",
  "Hablla Integration Worker: event-triggered integration worker connecting Hablla marketing platform to downstream reporting systems. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/hablla-integration-worker/",
  "Zenvia Integration Worker: SMS and messaging automation worker for Zenvia platform. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/zenvia-integration-worker/",
  "SIGE Integration Worker: SIGE ERP synchronization worker. Extracts and normalizes ERP records for reporting pipelines. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/sige-integration-worker/",
  "Omie Integration Worker: Omie ERP integration and data synchronization worker. JavaScript + GitHub Actions. Project page: https://pklavc.com/projects/omie-integration-worker/",
  // ── Blog posts ────────────────────────────────────────────────────────────
  "Blog: Patrick writes technical articles on backend engineering, automation, SaaS architecture, and AI systems. Blog listing: https://pklavc.com/blog/",
  "Blog post — Building Lavc Systems: Architecture of a Local Multi-Agent AI Platform (AI Platform Engineering, 14 min): FastAPI backend, React/Vite, Ollama local LLM, LangGraph multi-agent orchestration, ChromaDB RAG, HybridMemory, WebSocket observability. URL: https://pklavc.com/blog/lavc-systems-architecture/",
  "Blog post — Raw API Ingestion with GitHub Actions, Supabase, and SQL (Data Engineering, 10 min): Node.js workers, GitHub Actions schedules, Supabase raw_* SQL tables, idempotent external IDs, Hablla API, Zoho Creator API, Zenvia Voice API, SIGE ERP API, and replayable analytics architecture. URL: https://pklavc.com/blog/raw-api-ingestion-supabase-sql/",
  "Blog post — Backend Automation Systems: How to Reduce Manual Operations Without Breaking Reliability (Backend Engineering, 9 min): queue workers, auditability, retries, safe failure handling in production. URL: https://pklavc.com/blog/backend-automation-systems/",
  "Blog post — UX Analysis: How the GTA VI Official Website Builds Hype Through Motion and Storytelling (UX Analysis, 7 min): motion design, scroll storytelling, visual hierarchy, microinteractions. URL: https://pklavc.com/blog/gta-vi-website-ux-analysis/",
  "Blog post — Multi-Tenant SaaS Architecture: Patterns for Secure and Scalable APIs (SaaS Architecture, 10 min): tenant isolation, RBAC, queue workers, scalable API design. URL: https://pklavc.com/blog/multi-tenant-saas-architecture/",
  "Blog post — Event-Driven API Integrations: Designing for Retries, Idempotency, and Traceability (API Design, 8 min): idempotency, retries, traceability, safe webhook processing. URL: https://pklavc.com/blog/event-driven-api-integrations/",
  "Blog post — OAuth Token Management in Backend Workers: Secure Credential Flow for API Integrations (Security, 7 min): OAuth token acquisition, distribution, refresh in Node.js workers. URL: https://pklavc.com/blog/oauth-token-management/",
  "Blog post — Zero-Trust API Proxy Design: AES-256 Encryption and PII Detection in Python (Security Engineering, 9 min): AES-256 encryption, dynamic field masking, automated PII detection. URL: https://pklavc.com/blog/api-proxy-security-design/",
  "Blog post — ETL Pipelines in API Integration Workers: Data Extraction, Normalization, and Sync (Data Engineering, 8 min): ETL pipeline design in Node.js, CRM/ERP API extraction, payload normalization. URL: https://pklavc.com/blog/integration-worker-etl-pipelines/",
  "Blog post — Monorepo Architecture for Backend APIs: CI Workflows and Code Execution at Scale (Backend Architecture, 9 min): Node.js monorepo structure, code execution services, CI automation, QA coverage. URL: https://pklavc.com/blog/monorepo-backend-architecture/",
  "Blog post — Infrastructure Anomaly Detection and Self-Healing Backends in Python (Infrastructure, 10 min): predictive anomaly detection, autonomous recovery workflows in Python. URL: https://pklavc.com/blog/infrastructure-anomaly-detection/",
  "Blog post — Cloud Deployment Patterns: Container Orchestration, CI/CD, and Infrastructure as Code (DevOps, 8 min): Docker container orchestration, CI/CD pipelines, IaC for scalable backends. URL: https://pklavc.com/blog/cloud-deployment-patterns/",
  "Blog post — Web Performance for Immersive Marketing Sites: How to Keep Heavy Experiences Fluid (Web Performance, 7 min): lazy loading, image/video optimization, asset compression, visual effects trade-offs. URL: https://pklavc.com/blog/web-performance-immersive-marketing/",
  "Blog post — Data Engineering for Game Marketing Hype: Engagement Signals in AAA Launches (Data Engineering, 8 min): traffic observability, audience segmentation, hype forecasting through analytics pipelines. URL: https://pklavc.com/blog/aaa-game-launch-data-engineering/",
  "Blog post — AAA Game Leaks: Security Engineering, Asset Protection, and Social Engineering Risks (Security, 9 min): attack surfaces in content pipelines, digital asset protection, social engineering risks. URL: https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
  "Blog post — Global Launch Systems Architecture: What Happens When Millions Hit a Site at Once (Systems Architecture, 11 min): CDN strategy, cache topology, autoscaling, failure isolation for massive traffic. URL: https://pklavc.com/blog/global-launch-systems-architecture/",
  "Blog post — Automating AAA Launch Tracking: Bots, Site Change Monitoring, and Hype Intelligence (Automation, 8 min): monitoring AAA game launches, detecting site updates, hype tracking pipelines. URL: https://pklavc.com/blog/game-launch-monitoring-automation/",
  // ── Credentials ───────────────────────────────────────────────────────────
  "Current public credential: Member of GitHub Developer Program.",
  "Education and credentials context is available on the About page.",
  "Certifications (training only, NOT employment): Google Cybersecurity Professional Certificate, Google Data Analytics Professional Certificate, Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner, Datadog Foundation.",
  "Full certifications list: Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
];

export const MANUAL_RAG_SECTIONS: Array<{ key: string; keywords: string[]; content: string[]; contentPt?: string[]; contentEs?: string[] }> = [
  {
    key: "intro",
    keywords: [
      // PT
      "quem é o patrick", "quem e o patrick", "quem é você", "quem e voce", "quem é vc", "quem é ele",
      "me fale do patrick", "me fale de você", "me fale sobre o patrick", "fale do patrick", "fale sobre o patrick",
      "me apresenta", "me apresente", "se apresenta", "se apresente",
      "o que você faz", "o que voce faz", "qual é o patrick", "quem te criou", "quem criou você",
      "sobre o patrick", "sobre patrick", "patrick araujo", "pklavc",
      "desenvolvedor", "engenheiro de software",
      // EN
      "who is patrick", "who are you", "tell me about patrick", "about patrick",
      "introduce yourself", "who built you", "who created you", "who made you",
      "who is the developer", "who is the engineer", "who is behind",
      "what do you do", "what does patrick do", "describe patrick",
      // ES
      "quién es patrick", "quién eres", "háblame de patrick", "háblame sobre patrick",
      "preséntate", "quién te creó",
    ],
    content: [
      "Patrick Araujo is a backend and integration-focused software engineer.",
      "He works on automation systems, API integrations, ETL/data pipelines, and scalable backend architecture.",
      "Portfolio about page: https://pklavc.com/about/",
    ],
    contentPt: [
      "Patrick Araujo é um engenheiro de software com foco em backend e integrações.",
      "Trabalha com sistemas de automação, integrações de API, pipelines ETL e arquitetura de backend escalável.",
      "Página sobre: https://pklavc.com/about/",
    ],
    contentEs: [
      "Patrick Araujo es un ingeniero de software especializado en backend e integraciones.",
      "Trabaja en sistemas de automatización, integraciones de API, pipelines ETL y arquitectura de backend escalable.",
      "Página de presentación: https://pklavc.com/about/",
    ],
  },
  {
    key: "experience",
    keywords: [
      // PT
      "trabalho", "trabalhos", "emprego", "empregos", "empresa", "empresas",
      "onde trabalhou", "onde trabalha", "onde já trabalhou", "onde atuou", "onde atua",
      "carreira", "histórico profissional", "historico profissional", "experiência profissional", "experiencia profissional",
      "cargo", "cargos", "função", "funcao", "atuação", "atuacao",
      "histórico", "historico", "trajetória", "trajetoria",
      "clientes", "contratante", "contratantes",
      // EN
      "experience", "work history", "work experience", "career", "employment",
      "where did you work", "where have you worked", "where does patrick work",
      "job history", "jobs", "roles", "positions", "companies worked",
      "professional background", "professional history",
      // ES
      "experiencia laboral", "experiencia profesional", "historial laboral",
      "dónde trabajó", "empresa donde trabajó", "trayectoria", "carrera profesional",
    ],
    content: [
      "Patrick's employment history (actual companies he worked at as an employee):",
      "1. Loja do Sapo — Apple technical assistance. Role: Solutions Architect / Backend & Integration Engineer. Built ERP synchronization pipelines, API automation workers, and reporting infrastructure for variable-volume operational workflows.",
      "2. iCaiu — Apple technical assistance. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation, and reporting dashboards. Reduced processing time ~40% and saved ~3 hours/day per analyst.",
      "3. WR Auto Pecas — auto parts company. Earlier career. Backend automation and internal systems work.",
      "Full career and experience details: https://pklavc.com/about/",
    ],
    contentPt: [
      "Histórico de empregos do Patrick (empresas onde trabalhou de fato como funcionário):",
      "1. Loja do Sapo — assistência técnica especializada em produtos Apple. Cargo: Solutions Architect / Backend & Integration Engineer. Construiu pipelines de sincronização de ERP, workers de automação de API e infraestrutura de relatórios para fluxos operacionais de volume variável.",
      "2. iCaiu — assistência técnica especializada em produtos Apple. Cargo: Systems Integration Architect. Projetou workers de automação, pipelines ETL, sistemas de agregação de dados e dashboards. Reduziu tempo de processamento ~40% e economizou ~3h/dia por analista.",
      "3. WR Auto Peças — empresa de autopeças. Início de carreira. Automação de backend e sistemas internos.",
      "Detalhes completos da carreira: https://pklavc.com/about/",
    ],
    contentEs: [
      "Historial de empleo de Patrick (empresas donde trabajó como empleado):",
      "1. Loja do Sapo — asistencia técnica especializada en productos Apple. Cargo: Solutions Architect / Backend & Integration Engineer. Construyó pipelines de sincronización ERP, workers de automatización de API e infraestructura de reportes para flujos operativos de volumen variable.",
      "2. iCaiu — asistencia técnica especializada en productos Apple. Cargo: Systems Integration Architect. Diseñó workers de automatización, pipelines ETL, sistemas de agregación de datos y dashboards. Redujo el tiempo de procesamiento ~40% y ahorró ~3h/día por analista.",
      "3. WR Auto Peças — empresa de autopartes. Inicio de carrera. Automatización de backend y sistemas internos.",
      "Detalles completos de carrera: https://pklavc.com/about/",
    ],
  },
  {
    key: "projects",
    keywords: [
      // PT
      "projeto", "projetos", "portfólio", "portfolio",
      "o que construiu", "o que fez", "o que criou", "o que desenvolveu",
      "criou", "desenvolveu", "construiu", "fez",
      "sistema", "sistemas", "aplicação", "aplicacoes", "aplicacoes",
      "lista de projetos", "quais projetos", "quais são os projetos",
      "repositório", "repositorios", "repos",
      // EN
      "project", "projects", "what did you build", "what has patrick built",
      "what did patrick make", "what did patrick create",
      "built", "made", "created", "developed",
      "portfolio projects", "list of projects", "what projects",
      "applications", "apps", "repositories",
      // ES
      "proyecto", "proyectos", "portafolio",
      "qué construyó", "qué creó", "qué desarrolló",
    ],
    content: [
      "**Lavc Systems**",
      "• Local multi-agent AI platform — LangGraph, FastAPI, Ollama (qwen2.5-coder), ChromaDB RAG.",
      "https://pklavc.com/projects/lavc-systems/",
      "",
      "**Skyler Assistant**",
      "• Portfolio AI chatbot running on Cloudflare Workers with manual RAG and voice support.",
      "https://pklavc.com/projects/skyler-assistant/",
      "",
      "**Raw API Ingestion Pipeline**",
      "- Raw API ingestion pipeline using Node.js 20, GitHub Actions, Supabase/PostgreSQL raw_* tables, SQL-derived analytics, and idempotent external IDs for Hablla, Zoho Creator, Zenvia Voice, and SIGE ERP APIs.",
      "https://pklavc.com/projects/raw-api-ingestion-pipeline/",
      "",
      "**CodePulse Monorepo**",
      "• Online IDE with Fastify backend and 85%+ Playwright E2E test coverage.",
      "https://pklavc.com/projects/codepulse-monorepo/",
      "",
      "**Multi-Tenant SaaS Platform**",
      "• Enterprise backend with row-level tenancy, RBAC, BullMQ jobs. TypeScript + NestJS + PostgreSQL.",
      "https://pklavc.com/projects/multi-tenant-saas-platform/",
      "",
      "**Cipher Gate Proxy**",
      "• Zero-Trust API proxy with AES-256 encryption, dynamic data masking and PII detection. Python.",
      "https://pklavc.com/projects/cipher-gate-proxy/",
      "",
      "**Aegis Sentinel**",
      "• Autonomous infrastructure recovery engine with predictive anomaly detection and self-healing. Python.",
      "https://pklavc.com/projects/aegis-sentinel/",
      "",
      "**Cloud Deployment Showcase**",
      "• Cloud deployment patterns demonstration across AWS and GCP.",
      "https://pklavc.com/projects/cloud-deployment-showcase/",
      "",
      "**Event-Driven Integration Service**",
      "• Event-driven async API integration service with worker queues.",
      "https://pklavc.com/projects/event-driven-integration-service/",
      "",
      "**OS Resource Optimizer**",
      "• System resource monitoring and optimization tool.",
      "https://pklavc.com/projects/os-resource-optimizer/",
      "",
      "**Google Auth Worker**",
      "• OAuth orchestration worker in JavaScript + GitHub Actions for Google token management.",
      "https://pklavc.com/projects/google-auth-worker/",
      "",
      "**Zoho Integration Worker**",
      "• Automation worker for Zoho CRM/Desk API integration.",
      "https://pklavc.com/projects/zoho-integration-worker/",
      "",
      "**Hablla Integration Worker**",
      "• Automation worker for Hablla messaging API integration.",
      "https://pklavc.com/projects/hablla-integration-worker/",
      "",
      "**Zenvia Integration Worker**",
      "• Automation worker for Zenvia SMS/messaging API integration.",
      "https://pklavc.com/projects/zenvia-integration-worker/",
      "",
      "**SIGE Integration Worker**",
      "• Automation worker for SIGE ERP system integration.",
      "https://pklavc.com/projects/sige-integration-worker/",
      "",
      "**Omie Integration Worker**",
      "• Automation worker for Omie ERP API integration.",
      "https://pklavc.com/projects/omie-integration-worker/",
      "",
      "https://pklavc.com/projects/",
    ],
    contentPt: [
      "**Lavc Systems**",
      "• Plataforma de IA multi-agente local — LangGraph, FastAPI, Ollama (qwen2.5-coder), ChromaDB RAG.",
      "https://pklavc.com/projects/lavc-systems/",
      "",
      "**Skyler Assistant**",
      "• Chatbot de portfólio com IA rodando em Cloudflare Workers, RAG manual e suporte a voz.",
      "https://pklavc.com/projects/skyler-assistant/",
      "",
      "**Raw API Ingestion Pipeline**",
      "- Pipeline de ingestao raw de APIs com Node.js 20, GitHub Actions, Supabase/PostgreSQL raw_* tables, analytics em SQL e external_id idempotente para Hablla, Zoho Creator, Zenvia Voice e SIGE ERP.",
      "https://pklavc.com/projects/raw-api-ingestion-pipeline/",
      "",
      "**CodePulse Monorepo**",
      "• IDE online com backend Fastify e cobertura de testes E2E 85%+ com Playwright.",
      "https://pklavc.com/projects/codepulse-monorepo/",
      "",
      "**Multi-Tenant SaaS Platform**",
      "• Backend enterprise com tenancy por linha, RBAC e jobs BullMQ. TypeScript + NestJS + PostgreSQL.",
      "https://pklavc.com/projects/multi-tenant-saas-platform/",
      "",
      "**Cipher Gate Proxy**",
      "• Proxy API Zero-Trust com criptografia AES-256, mascaramento dinâmico de dados e detecção de PII. Python.",
      "https://pklavc.com/projects/cipher-gate-proxy/",
      "",
      "**Aegis Sentinel**",
      "• Motor autônomo de recuperação de infraestrutura com detecção preditiva de anomalias e autocura. Python.",
      "https://pklavc.com/projects/aegis-sentinel/",
      "",
      "**Cloud Deployment Showcase**",
      "• Demonstração de padrões de deploy em cloud na AWS e GCP.",
      "https://pklavc.com/projects/cloud-deployment-showcase/",
      "",
      "**Event-Driven Integration Service**",
      "• Serviço de integração de API assíncrono e orientado a eventos com filas de workers.",
      "https://pklavc.com/projects/event-driven-integration-service/",
      "",
      "**OS Resource Optimizer**",
      "• Ferramenta de monitoramento e otimização de recursos do sistema operacional.",
      "https://pklavc.com/projects/os-resource-optimizer/",
      "",
      "**Google Auth Worker**",
      "• Worker de orquestração OAuth em JavaScript + GitHub Actions para gestão de tokens Google.",
      "https://pklavc.com/projects/google-auth-worker/",
      "",
      "**Zoho Integration Worker**",
      "• Worker de automação para integração com a API do Zoho CRM/Desk.",
      "https://pklavc.com/projects/zoho-integration-worker/",
      "",
      "**Hablla Integration Worker**",
      "• Worker de automação para integração com a API de mensagens da Hablla.",
      "https://pklavc.com/projects/hablla-integration-worker/",
      "",
      "**Zenvia Integration Worker**",
      "• Worker de automação para integração com a API SMS/mensagens da Zenvia.",
      "https://pklavc.com/projects/zenvia-integration-worker/",
      "",
      "**SIGE Integration Worker**",
      "• Worker de automação para integração com o sistema ERP SIGE.",
      "https://pklavc.com/projects/sige-integration-worker/",
      "",
      "**Omie Integration Worker**",
      "• Worker de automação para integração com a API do ERP Omie.",
      "https://pklavc.com/projects/omie-integration-worker/",
      "",
      "https://pklavc.com/projects/",
    ],
    contentEs: [
      "**Lavc Systems**",
      "• Plataforma de IA multi-agente local — LangGraph, FastAPI, Ollama (qwen2.5-coder), ChromaDB RAG.",
      "https://pklavc.com/projects/lavc-systems/",
      "",
      "**Skyler Assistant**",
      "• Chatbot de portafolio con IA en Cloudflare Workers, RAG manual y soporte de voz.",
      "https://pklavc.com/projects/skyler-assistant/",
      "",
      "**Raw API Ingestion Pipeline**",
      "- Pipeline de ingesta raw de APIs con Node.js 20, GitHub Actions, Supabase/PostgreSQL raw_* tables, analytics SQL e external_id idempotente para Hablla, Zoho Creator, Zenvia Voice y SIGE ERP.",
      "https://pklavc.com/projects/raw-api-ingestion-pipeline/",
      "",
      "**CodePulse Monorepo**",
      "• IDE online con backend Fastify y cobertura de tests E2E 85%+ con Playwright.",
      "https://pklavc.com/projects/codepulse-monorepo/",
      "",
      "**Multi-Tenant SaaS Platform**",
      "• Backend enterprise con tenancy por fila, RBAC y jobs BullMQ. TypeScript + NestJS + PostgreSQL.",
      "https://pklavc.com/projects/multi-tenant-saas-platform/",
      "",
      "**Cipher Gate Proxy**",
      "• Proxy API Zero-Trust con cifrado AES-256, enmascaramiento dinámico de datos y detección de PII. Python.",
      "https://pklavc.com/projects/cipher-gate-proxy/",
      "",
      "**Aegis Sentinel**",
      "• Motor autónomo de recuperación de infraestructura con detección predictiva de anomalías y autocurado. Python.",
      "https://pklavc.com/projects/aegis-sentinel/",
      "",
      "**Cloud Deployment Showcase**",
      "• Demostración de patrones de despliegue en la nube con AWS y GCP.",
      "https://pklavc.com/projects/cloud-deployment-showcase/",
      "",
      "**Event-Driven Integration Service**",
      "• Servicio de integración de API asíncrono orientado a eventos con colas de workers.",
      "https://pklavc.com/projects/event-driven-integration-service/",
      "",
      "**OS Resource Optimizer**",
      "• Herramienta de monitoreo y optimización de recursos del sistema operativo.",
      "https://pklavc.com/projects/os-resource-optimizer/",
      "",
      "**Google Auth Worker**",
      "• Worker de orquestación OAuth en JavaScript + GitHub Actions para gestión de tokens Google.",
      "https://pklavc.com/projects/google-auth-worker/",
      "",
      "**Zoho Integration Worker**",
      "• Worker de automatización para integración con la API de Zoho CRM/Desk.",
      "https://pklavc.com/projects/zoho-integration-worker/",
      "",
      "**Hablla Integration Worker**",
      "• Worker de automatización para integración con la API de mensajería Hablla.",
      "https://pklavc.com/projects/hablla-integration-worker/",
      "",
      "**Zenvia Integration Worker**",
      "• Worker de automatización para integración con la API SMS/mensajería de Zenvia.",
      "https://pklavc.com/projects/zenvia-integration-worker/",
      "",
      "**SIGE Integration Worker**",
      "• Worker de automatización para integración con el sistema ERP SIGE.",
      "https://pklavc.com/projects/sige-integration-worker/",
      "",
      "**Omie Integration Worker**",
      "• Worker de automatización para integración con la API del ERP Omie.",
      "https://pklavc.com/projects/omie-integration-worker/",
      "",
      "https://pklavc.com/projects/",
    ],
  },
  {
    key: "blog",
    keywords: [
      // PT
      "blog", "publicação", "publicações", "publicacao", "publicacoes",
      "postagem", "postagens",
      "artigo", "artigos", "post", "posts",
      "escreveu", "escrito", "escrita", "conteúdo", "conteudo",
      "o que escreveu", "o que publicou", "o que tem no blog",
      "leitura", "leituras", "texto", "textos",
      // EN
      "article", "articles", "writing", "wrote", "written",
      "what did patrick write", "what has patrick written",
      "blog posts", "content", "reads",
      // ES
      "artículo", "artículos", "publicación", "publicaciones",
      "escribió", "contenido",
    ],
    content: [
      "**Building Lavc Systems**",
      "• How Patrick built a local multi-agent AI platform with LangGraph, FastAPI, Ollama and ChromaDB. 14 min.",
      "https://pklavc.com/blog/lavc-systems-architecture/",
      "",
      "**Raw API Ingestion**",
      "- Architecture article on Node.js workers, GitHub Actions schedules, Supabase raw_* SQL tables, idempotent external IDs, Hablla API, Zoho Creator API, Zenvia Voice API, SIGE ERP API, and replayable analytics. 10 min.",
      "https://pklavc.com/blog/raw-api-ingestion-supabase-sql/",
      "",
      "**Backend Automation Systems**",
      "• Building automation workers that eliminated manual operations. 9 min.",
      "https://pklavc.com/blog/backend-automation-systems/",
      "",
      "**UX Analysis: GTA VI Website**",
      "• Full UX breakdown of the official GTA VI launch website. 7 min.",
      "https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "",
      "**Multi-Tenant SaaS Architecture**",
      "• Row-level tenancy, RBAC and background jobs in a NestJS + PostgreSQL platform. 10 min.",
      "https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "",
      "**Event-Driven API Integrations**",
      "• Patterns for async event-driven integrations with worker queues. 8 min.",
      "https://pklavc.com/blog/event-driven-api-integrations/",
      "",
      "**OAuth Token Management**",
      "• Managing OAuth tokens inside Cloudflare Workers. 7 min.",
      "https://pklavc.com/blog/oauth-token-management/",
      "",
      "**Zero-Trust API Proxy Design**",
      "• AES-256 encryption, dynamic data masking and automated PII detection. 9 min.",
      "https://pklavc.com/blog/api-proxy-security-design/",
      "",
      "**ETL Pipelines in Integration Workers**",
      "• Building ETL data pipelines inside integration workers. 8 min.",
      "https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "",
      "**Monorepo Architecture for Backend APIs**",
      "• Structuring a monorepo for scalable backend APIs. 9 min.",
      "https://pklavc.com/blog/monorepo-backend-architecture/",
      "",
      "**Infrastructure Anomaly Detection**",
      "• Autonomous anomaly detection and self-healing infrastructure. 10 min.",
      "https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "",
      "**Cloud Deployment Patterns**",
      "• Tradeoffs and patterns for cloud deployments across AWS and GCP. 8 min.",
      "https://pklavc.com/blog/cloud-deployment-patterns/",
      "",
      "**Web Performance for Immersive Marketing Sites**",
      "• Performance optimization techniques for immersive marketing websites. 7 min.",
      "https://pklavc.com/blog/web-performance-immersive-marketing/",
      "",
      "**Data Engineering for AAA Game Launches**",
      "• Data pipelines tracking hype and launch metrics for AAA games. 8 min.",
      "https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "",
      "**AAA Game Leaks: Security Engineering**",
      "• Security engineering analysis of high-profile AAA game leak incidents. 9 min.",
      "https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "",
      "**Global Launch Systems Architecture**",
      "• Architecture for simultaneous global game launches. 11 min.",
      "https://pklavc.com/blog/global-launch-systems-architecture/",
      "",
      "**Automating AAA Launch Tracking**",
      "• Automation systems for tracking AAA game launch campaigns. 8 min.",
      "https://pklavc.com/blog/game-launch-monitoring-automation/",
      "",
      "https://pklavc.com/blog/",
    ],
    contentPt: [
      "**Building Lavc Systems**",
      "• Como Patrick construiu uma plataforma de IA multi-agente local com LangGraph, FastAPI, Ollama e ChromaDB. 14 min.",
      "https://pklavc.com/blog/lavc-systems-architecture/",
      "",
      "**Raw API Ingestion**",
      "- Artigo de arquitetura sobre workers Node.js, agendamentos GitHub Actions, tabelas Supabase raw_* em SQL, external IDs idempotentes, APIs Hablla, Zoho Creator, Zenvia Voice e SIGE ERP, e analytics reprocessavel. 10 min.",
      "https://pklavc.com/blog/raw-api-ingestion-supabase-sql/",
      "",
      "**Backend Automation Systems**",
      "• Construção de workers de automação que eliminaram operações manuais. 9 min.",
      "https://pklavc.com/blog/backend-automation-systems/",
      "",
      "**Análise UX: Site do GTA VI**",
      "• Análise completa de UX do site oficial de lançamento do GTA VI. 7 min.",
      "https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "",
      "**Arquitetura Multi-Tenant SaaS**",
      "• Tenancy por linha, RBAC e jobs em background numa plataforma NestJS + PostgreSQL. 10 min.",
      "https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "",
      "**Integrações de API Orientadas a Eventos**",
      "• Padrões para integrações assíncronas orientadas a eventos com filas de workers. 8 min.",
      "https://pklavc.com/blog/event-driven-api-integrations/",
      "",
      "**Gestão de Tokens OAuth**",
      "• Gerenciando tokens OAuth dentro de Cloudflare Workers. 7 min.",
      "https://pklavc.com/blog/oauth-token-management/",
      "",
      "**Proxy API Zero-Trust**",
      "• Criptografia AES-256, mascaramento dinâmico de dados e detecção automatizada de PII. 9 min.",
      "https://pklavc.com/blog/api-proxy-security-design/",
      "",
      "**Pipelines ETL em Workers de Integração**",
      "• Construção de pipelines ETL dentro de workers de integração. 8 min.",
      "https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "",
      "**Arquitetura Monorepo para APIs Backend**",
      "• Estruturando um monorepo para APIs backend escaláveis. 9 min.",
      "https://pklavc.com/blog/monorepo-backend-architecture/",
      "",
      "**Detecção de Anomalias em Infraestrutura**",
      "• Detecção autônoma de anomalias e infraestrutura com autocura. 10 min.",
      "https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "",
      "**Padrões de Deploy em Cloud**",
      "• Tradeoffs e padrões de deploy em cloud na AWS e GCP. 8 min.",
      "https://pklavc.com/blog/cloud-deployment-patterns/",
      "",
      "**Performance Web para Sites de Marketing Imersivo**",
      "• Técnicas de otimização de performance para sites de marketing imersivos. 7 min.",
      "https://pklavc.com/blog/web-performance-immersive-marketing/",
      "",
      "**Engenharia de Dados para Lançamentos AAA**",
      "• Pipelines de dados rastreando hype e métricas de lançamento de jogos AAA. 8 min.",
      "https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "",
      "**Vazamentos de Jogos AAA: Engenharia de Segurança**",
      "• Análise de engenharia de segurança nos vazamentos de jogos AAA de alto perfil. 9 min.",
      "https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "",
      "**Arquitetura de Sistemas para Lançamentos Globais**",
      "• Arquitetura para lançamentos globais simultâneos de jogos. 11 min.",
      "https://pklavc.com/blog/global-launch-systems-architecture/",
      "",
      "**Automatizando o Rastreamento de Lançamentos AAA**",
      "• Sistemas de automação para rastreamento de campanhas de lançamento AAA. 8 min.",
      "https://pklavc.com/blog/game-launch-monitoring-automation/",
      "",
      "https://pklavc.com/blog/",
    ],
    contentEs: [
      "**Building Lavc Systems**",
      "• Cómo Patrick construyó una plataforma de IA multi-agente local con LangGraph, FastAPI, Ollama y ChromaDB. 14 min.",
      "https://pklavc.com/blog/lavc-systems-architecture/",
      "",
      "**Raw API Ingestion**",
      "- Articulo de arquitectura sobre workers Node.js, schedules de GitHub Actions, tablas Supabase raw_* en SQL, external IDs idempotentes, APIs Hablla, Zoho Creator, Zenvia Voice y SIGE ERP, y analytics reprocesable. 10 min.",
      "https://pklavc.com/blog/raw-api-ingestion-supabase-sql/",
      "",
      "**Backend Automation Systems**",
      "• Construcción de workers de automatización que eliminaron operaciones manuales. 9 min.",
      "https://pklavc.com/blog/backend-automation-systems/",
      "",
      "**Análisis UX: Sitio de GTA VI**",
      "• Análisis completo de UX del sitio oficial de lanzamiento de GTA VI. 7 min.",
      "https://pklavc.com/blog/gta-vi-website-ux-analysis/",
      "",
      "**Arquitectura Multi-Tenant SaaS**",
      "• Tenancy por fila, RBAC y jobs en background en una plataforma NestJS + PostgreSQL. 10 min.",
      "https://pklavc.com/blog/multi-tenant-saas-architecture/",
      "",
      "**Integraciones de API Orientadas a Eventos**",
      "• Patrones para integraciones asíncronas orientadas a eventos con colas de workers. 8 min.",
      "https://pklavc.com/blog/event-driven-api-integrations/",
      "",
      "**Gestión de Tokens OAuth**",
      "• Gestionando tokens OAuth dentro de Cloudflare Workers. 7 min.",
      "https://pklavc.com/blog/oauth-token-management/",
      "",
      "**Proxy API Zero-Trust**",
      "• Cifrado AES-256, enmascaramiento dinámico de datos y detección automatizada de PII. 9 min.",
      "https://pklavc.com/blog/api-proxy-security-design/",
      "",
      "**Pipelines ETL en Workers de Integración**",
      "• Construcción de pipelines ETL dentro de workers de integración. 8 min.",
      "https://pklavc.com/blog/integration-worker-etl-pipelines/",
      "",
      "**Arquitectura Monorepo para APIs Backend**",
      "• Estructurando un monorepo para APIs backend escalables. 9 min.",
      "https://pklavc.com/blog/monorepo-backend-architecture/",
      "",
      "**Detección de Anomalías en Infraestructura**",
      "• Detección autónoma de anomalías e infraestructura con autocurado. 10 min.",
      "https://pklavc.com/blog/infrastructure-anomaly-detection/",
      "",
      "**Patrones de Despliegue en la Nube**",
      "• Tradeoffs y patrones de despliegue en la nube con AWS y GCP. 8 min.",
      "https://pklavc.com/blog/cloud-deployment-patterns/",
      "",
      "**Rendimiento Web para Sitios de Marketing Inmersivo**",
      "• Técnicas de optimización de rendimiento para sitios de marketing inmersivos. 7 min.",
      "https://pklavc.com/blog/web-performance-immersive-marketing/",
      "",
      "**Ingeniería de Datos para Lanzamientos AAA**",
      "• Pipelines de datos rastreando hype y métricas de lanzamiento de juegos AAA. 8 min.",
      "https://pklavc.com/blog/aaa-game-launch-data-engineering/",
      "",
      "**Filtraciones de Juegos AAA: Ingeniería de Seguridad**",
      "• Análisis de ingeniería de seguridad en filtraciones de alto perfil de juegos AAA. 9 min.",
      "https://pklavc.com/blog/aaa-game-leaks-security-engineering/",
      "",
      "**Arquitectura de Sistemas para Lanzamientos Globales**",
      "• Arquitectura para lanzamientos globales simultáneos de juegos. 11 min.",
      "https://pklavc.com/blog/global-launch-systems-architecture/",
      "",
      "**Automatizando el Seguimiento de Lanzamientos AAA**",
      "• Sistemas de automatización para rastrear campañas de lanzamiento AAA. 8 min.",
      "https://pklavc.com/blog/game-launch-monitoring-automation/",
      "",
      "https://pklavc.com/blog/",
    ],
  },
  {
    key: "contact",
    keywords: [
      // PT
      "contato", "como entrar em contato", "como falar", "como contratar", "como te contratar",
      "email", "e-mail", "linkedin", "mensagem", "mandar mensagem",
      "redes sociais", "redes", "mídia", "midia",
      "como chamar", "como alcancar", "como alcançar",
      "disponivel", "disponível", "disponibilidade",
      // EN
      "contact", "how to contact", "how to hire", "hire patrick",
      "reach out", "get in touch", "send a message",
      "social media", "social links", "github",
      "available for", "availability",
      // ES
      "contacto", "cómo contactar", "contratar", "correo", "mensaje",
      "redes sociales", "disponible",
    ],
    content: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portfolio: https://pklavc.com",
    ],
    contentPt: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portfólio: https://pklavc.com",
    ],
    contentEs: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portafolio: https://pklavc.com",
    ],
  },
  {
    key: "certificates",
    keywords: [
      // PT
      "certificado", "certificados", "certificação", "certificações", "certificacao", "certificacoes",
      "curso", "cursos", "o que estudou", "o que fez de curso", "cursos que fez",
      "educação", "educacao", "formação", "formacao",
      "credencial", "credenciais", "treinamento", "treinamentos",
      "aprendizado", "qualificação", "qualificacoes", "qualificações",
      "o que estudou", "estudo", "estudos",
      // EN
      "certificate", "certificates", "certification", "certifications",
      "course", "courses", "education", "training",
      "credential", "credentials", "learning", "qualification", "qualifications",
      "what did patrick study", "what has patrick studied",
      // ES
      "certificado", "certificados", "certificación", "certificaciones",
      "curso", "cursos", "educación", "formación", "entrenamiento",
    ],
    content: [
      "**Google**",
      "- Google Data Analytics",
      "- Foundations: Data, Data, Everywhere",
      "- Ask Questions to Make Data-Driven Decisions",
      "- Prepare Data for Exploration",
      "- Process Data from Dirty to Clean",
      "- Analyze Data to Answer Questions",
      "- Share Data Through the Art of Visualization",
      "- Introduction to Data Analysis Using Python",
      "- Google Data Analytics Capstone: Complete a Case Study",
      "- Accelerate Your Job Search with AI",
      "- Google Cybersecurity",
      "- Foundations of Cybersecurity",
      "- Play It Safe: Manage Security Risks",
      "- Connect and Protect: Networks and Network Security",
      "- Tools of the Trade: Linux and SQL",
      "- Assets, Threats, and Vulnerabilities",
      "- Sound the Alarm: Detection and Response",
      "- Automate Cybersecurity Tasks with Python",
      "- Put It to Work: Prepare for Cybersecurity Jobs",
      "- Google AI Essentials",
      "- Google Prompting Essentials",
      "- Stay Ahead of the AI Curve",
      "- Use AI Responsibly",
      "- Discover the Art of Prompting",
      "- Maximize Productivity With AI Tools",
      "- Introduction to AI",
      "- Use AI as a Creative or Expert Partner",
      "- Speed Up Data Analysis and Presentation Building",
      "- Design Prompts for Everyday Work Tasks",
      "- Start Writing Prompts like a Pro",
      "- Foundations of Project Management",
      "- Project Initiation: Starting a Successful Project",
      "",
      "**AWS**",
      "- AWS Cloud Quest: Cloud Practitioner",
      "",
      "**Datadog**",
      "- Datadog Foundation",
      "",
      "**Alura**",
      "- Imersão Front-End com IA",
      "",
      "**Santander / DIO**",
      "- Atividade - Plugin 24.1",
      "",
      "Education details: https://pklavc.com/about/",
    ],
    contentPt: [
      "**Google**",
      "- Google Data Analytics",
      "- Foundations: Data, Data, Everywhere",
      "- Ask Questions to Make Data-Driven Decisions",
      "- Prepare Data for Exploration",
      "- Process Data from Dirty to Clean",
      "- Analyze Data to Answer Questions",
      "- Share Data Through the Art of Visualization",
      "- Introduction to Data Analysis Using Python",
      "- Google Data Analytics Capstone: Complete a Case Study",
      "- Accelerate Your Job Search with AI",
      "- Google Cybersecurity",
      "- Foundations of Cybersecurity",
      "- Play It Safe: Manage Security Risks",
      "- Connect and Protect: Networks and Network Security",
      "- Tools of the Trade: Linux and SQL",
      "- Assets, Threats, and Vulnerabilities",
      "- Sound the Alarm: Detection and Response",
      "- Automate Cybersecurity Tasks with Python",
      "- Put It to Work: Prepare for Cybersecurity Jobs",
      "- Google AI Essentials",
      "- Google Prompting Essentials",
      "- Stay Ahead of the AI Curve",
      "- Use AI Responsibly",
      "- Discover the Art of Prompting",
      "- Maximize Productivity With AI Tools",
      "- Introduction to AI",
      "- Use AI as a Creative or Expert Partner",
      "- Speed Up Data Analysis and Presentation Building",
      "- Design Prompts for Everyday Work Tasks",
      "- Start Writing Prompts like a Pro",
      "- Fundamentos do gerenciamento de projetos",
      "- Início do projeto: Como começar um projeto bem-sucedido",
      "",
      "**AWS**",
      "- AWS Cloud Quest: Cloud Practitioner",
      "",
      "**Datadog**",
      "- Datadog Foundation",
      "",
      "**Alura**",
      "- Imersão Front-End com IA",
      "",
      "**Santander / DIO**",
      "- Atividade - Plugin 24.1",
      "",
      "Detalhes de educação: https://pklavc.com/about/",
    ],
    contentEs: [
      "**Google**",
      "- Google Data Analytics",
      "- Foundations: Data, Data, Everywhere",
      "- Ask Questions to Make Data-Driven Decisions",
      "- Prepare Data for Exploration",
      "- Process Data from Dirty to Clean",
      "- Analyze Data to Answer Questions",
      "- Share Data Through the Art of Visualization",
      "- Introduction to Data Analysis Using Python",
      "- Google Data Analytics Capstone: Complete a Case Study",
      "- Accelerate Your Job Search with AI",
      "- Google Cybersecurity",
      "- Foundations of Cybersecurity",
      "- Play It Safe: Manage Security Risks",
      "- Connect and Protect: Networks and Network Security",
      "- Tools of the Trade: Linux and SQL",
      "- Assets, Threats, and Vulnerabilities",
      "- Sound the Alarm: Detection and Response",
      "- Automate Cybersecurity Tasks with Python",
      "- Put It to Work: Prepare for Cybersecurity Jobs",
      "- Google AI Essentials",
      "- Google Prompting Essentials",
      "- Stay Ahead of the AI Curve",
      "- Use AI Responsibly",
      "- Discover the Art of Prompting",
      "- Maximize Productivity With AI Tools",
      "- Introduction to AI",
      "- Use AI as a Creative or Expert Partner",
      "- Speed Up Data Analysis and Presentation Building",
      "- Design Prompts for Everyday Work Tasks",
      "- Start Writing Prompts like a Pro",
      "- Fundamentos de la gestión de proyectos",
      "- Inicio del proyecto: Cómo comenzar un proyecto exitoso",
      "",
      "**AWS**",
      "- AWS Cloud Quest: Cloud Practitioner",
      "",
      "**Datadog**",
      "- Datadog Foundation",
      "",
      "**Alura**",
      "- Imersão Front-End com IA",
      "",
      "**Santander / DIO**",
      "- Atividade - Plugin 24.1",
      "",
      "Detalles de educación: https://pklavc.com/about/",
    ],
  },
];
