export const MANUAL_RAG_CONTEXT = [
  "Name: Patrick Araujo.",
  "Primary roles: Backend Software Engineer, API Integration Engineer, Solutions Architect.",
  "Website: https://pklavc.com",
  "About page: https://pklavc.com/about/",
  "Projects page: https://pklavc.com/projects/",
  "Blog page: https://pklavc.com/blog/",
  "GitHub profile: https://github.com/PkLavc",
  "LinkedIn profile: https://www.linkedin.com/in/pklavc/",
  "Contact email: contact@pklavc.com",
  "Core stack: Python, Node.js, SQL, JavaScript, PostgreSQL, REST APIs, AWS, Google Cloud, Zoho, Deluge.",
  "Architecture focus: automation, API integrations, ETL pipelines, backend scalability, system design, integration governance.",
  "Measured impact: 8K-12K daily transactions, ~3 hours/day saved per analyst, ~40% faster processing, ~35-40% faster APIs.",
  // ── Employment history (actual jobs) ──────────────────────────────────────
  "EMPLOYMENT HISTORY (companies Patrick actually worked at as an employee):",
  "Job 1 — Loja do Sapo: e-commerce company. Role: Solutions Architect / Backend & Integration Engineer. Built ERP sync pipelines, API automation workers, and operational reporting infrastructure handling 8K-12K daily transactions.",
  "Job 2 — iCaiu: tech/operations company. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation systems, and reporting dashboards. Reduced processing time ~40% and analyst manual work ~3 hours/day.",
  "Job 3 — WR Auto Pecas: auto parts company. Earlier career; backend automation and internal systems work.",
  // ── Critical disambiguation ───────────────────────────────────────────────
  "IMPORTANT — NEVER confuse certification providers with employers: Google, AWS, Datadog, and Coursera are ONLY certification/training providers. Patrick has NEVER worked at Google, AWS, or Datadog as an employee.",
  "IMPORTANT — PkLavc is Patrick's personal portfolio handle/brand and the domain pklavc.com is his portfolio website, NOT a company he founded or works at.",
  // ── Projects ──────────────────────────────────────────────────────────────
  "Projects (full list): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
  "Lavc Systems: local desktop/web AI platform — multi-agent orchestration (LangGraph), FastAPI backend, React/Vite/TypeScript frontend, Ollama local LLM (qwen2.5-coder:7b), ChromaDB RAG, HybridMemory (SQLite + ChromaDB), Kanban task management, APScheduler, autonomous goals, real-time WebSocket observability. Project page: https://pklavc.com/projects/lavc-systems/",
  "Skyler Assistant: public portfolio AI chatbot running on Cloudflare Workers — manual RAG, provider fallback (Groq → OpenRouter), Web Speech API voice, D1 + KV session memory. Demo: https://pklavc.com/projects/skyler-assistant/demo/ Project page: https://pklavc.com/projects/skyler-assistant/",
  "CodePulse Monorepo: online IDE built as a standalone HTML app with Fastify backend on Render and 85%+ Playwright E2E coverage. Project page: https://pklavc.com/projects/codepulse-monorepo/",
  "Google Auth Worker: OAuth orchestration worker in JavaScript + GitHub Actions for issuing Google tokens and triggering downstream jobs. Project page: https://pklavc.com/projects/google-auth-worker/",
  "Multi-Tenant SaaS Platform: enterprise-grade backend with row-level tenancy, RBAC, BullMQ background jobs. TypeScript + NestJS + PostgreSQL. Project page: https://pklavc.com/projects/multi-tenant-saas-platform/",
  "Cipher Gate Proxy: Zero-Trust proxy with AES-256 encryption, dynamic data masking, and automated PII detection. Python. Project page: https://pklavc.com/projects/cipher-gate-proxy/",
  "Aegis Sentinel: autonomous infrastructure recovery engine with predictive anomaly detection and self-healing. Python. Project page: https://pklavc.com/projects/aegis-sentinel/",
  "Cloud Deployment Showcase: production-ready container orchestration, IaC, and CI/CD. Docker + Nginx + GitHub Actions. Project page: https://pklavc.com/projects/cloud-deployment-showcase/",
  "Event-Driven Integration Service: reliable webhook processing with HMAC security and distributed tracing. NestJS + BullMQ + OpenTelemetry. Project page: https://pklavc.com/projects/event-driven-integration-service/",
  "OS Resource Optimizer: high-performance CPU scheduling and memory allocation engine. C++17. Project page: https://pklavc.com/projects/os-resource-optimizer/",
  // ── Credentials ───────────────────────────────────────────────────────────
  "Current public credential: Member of GitHub Developer Program.",
  "Education and credentials context is available on the About page.",
  "Certifications (training only, NOT employment): Google Cybersecurity Professional Certificate(v.2), Google Data Analytics Professional Certificate(v.3), Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner badge, Datadog Foundation.",
  "Full certifications list: Google Cybersecurity Professional Certificate(v.2); Google Data Analytics Professional Certificate(v.3); Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google AI Essentials V1 - Badge; Google Prompting Essentials - Badge; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; AWS Cloud Quest: Cloud Practitioner - Training Badge; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
];

export const MANUAL_RAG_SECTIONS: Array<{ key: string; keywords: string[]; content: string[] }> = [
  {
    key: "intro",
    keywords: ["who", "quem", "patrick", "pklavc", "about", "sobre", "profile", "perfil"],
    content: [
      "Patrick Araujo is a backend and integration-focused software engineer.",
      "He works on automation systems, API integrations, ETL/data pipelines, and scalable backend architecture.",
      "Portfolio about page: https://pklavc.com/about/",
    ],
  },
  {
    key: "experience",
    keywords: ["experience", "experiencia", "trabalho", "trabalhos", "emprego", "empregos", "work", "career", "carreira", "empresa", "empresas", "companies", "job", "jobs", "cargo", "cargos", "historico", "histórico", "professional"],
    content: [
      "Patrick's employment history (actual companies he worked at as an employee):",
      "1. Loja do Sapo — e-commerce company. Role: Solutions Architect / Backend & Integration Engineer. Built ERP synchronization pipelines, API automation workers, and reporting infrastructure handling 8K-12K daily transactions.",
      "2. iCaiu — tech/operations company. Role: Systems Integration Architect. Designed automation workers, ETL pipelines, multi-source data aggregation, and reporting dashboards. Reduced processing time ~40% and saved ~3 hours/day per analyst.",
      "3. WR Auto Pecas — auto parts company. Earlier career. Backend automation and internal systems work.",
      "CRITICAL NOTE: Google, AWS, and Datadog are ONLY certification/training providers — they are NOT employers. Patrick never worked at Google, AWS, or Datadog.",
      "CRITICAL NOTE: PkLavc / pklavc.com is Patrick's personal portfolio brand, not a company.",
      "Full career and experience details: https://pklavc.com/about/",
    ],
  },
  {
    key: "projects",
    keywords: ["project", "projeto", "projetos", "projects", "github", "repo", "portfolio", "worker", "saas", "integration", "skyler", "lavc", "codepulse", "cipher", "aegis", "sentinel", "monorepo"],
    content: [
      "Patrick's projects (full list): Lavc Systems, Skyler Assistant, Google Auth Worker, Zoho Integration Worker, Hablla Integration Worker, Zenvia Integration Worker, SIGE Integration Worker, Omie Integration Worker, CodePulse Monorepo, OS Resource Optimizer, Multi-Tenant SaaS Platform, Cipher Gate Proxy, Event-Driven Integration Service, Aegis Sentinel, Cloud Deployment Showcase.",
      "Lavc Systems — local AI orchestration platform: https://pklavc.com/projects/lavc-systems/",
      "Skyler Assistant — portfolio AI chatbot: https://pklavc.com/projects/skyler-assistant/",
      "CodePulse Monorepo — online IDE: https://pklavc.com/projects/codepulse-monorepo/",
      "Multi-Tenant SaaS Platform: https://pklavc.com/projects/multi-tenant-saas-platform/",
      "Cipher Gate Proxy: https://pklavc.com/projects/cipher-gate-proxy/",
      "Aegis Sentinel: https://pklavc.com/projects/aegis-sentinel/",
      "Cloud Deployment Showcase: https://pklavc.com/projects/cloud-deployment-showcase/",
      "Event-Driven Integration Service: https://pklavc.com/projects/event-driven-integration-service/",
      "OS Resource Optimizer: https://pklavc.com/projects/os-resource-optimizer/",
      "Google Auth Worker: https://pklavc.com/projects/google-auth-worker/",
      "All projects listing: https://pklavc.com/projects/",
      "GitHub profile: https://github.com/PkLavc",
    ],
  },
  {
    key: "blog",
    keywords: ["blog", "article", "artigo", "post", "conteudo", "content", "writing", "escrita"],
    content: [
      "Blog topics include backend automation, multi-tenant SaaS, event-driven APIs, OAuth token management, ETL, monorepo backend architecture, cloud deployment patterns, AI platform engineering, and LangGraph/ChromaDB.",
      "Blog listing: https://pklavc.com/blog/",
    ],
  },
  {
    key: "contact",
    keywords: ["contact", "contato", "email", "linkedin", "hire", "contratar", "github", "reach", "falar", "mensagem", "message"],
    content: [
      "Email: contact@pklavc.com",
      "LinkedIn: https://www.linkedin.com/in/pklavc/",
      "GitHub: https://github.com/PkLavc",
      "Portfolio: https://pklavc.com",
    ],
  },
  {
    key: "certificates",
    keywords: ["certificate", "certificates", "certificado", "certificados", "credential", "credentials", "course", "courses", "curso", "cursos", "education", "educacao", "educação", "formacao", "formação", "certification"],
    content: [
      "Publicly highlighted credential: Member of GitHub Developer Program.",
      "These are CERTIFICATIONS (training), NOT employment. Certification providers include Google, AWS, and Datadog — Patrick never worked at these companies.",
      "Key certifications: Google Cybersecurity Professional Certificate(v.2), Google Data Analytics Professional Certificate(v.3), Google AI Essentials, Google Prompting Essentials, AWS Cloud Quest: Cloud Practitioner badge, Datadog Foundation.",
      "Full certifications list: Google Cybersecurity Professional Certificate(v.2); Google Data Analytics Professional Certificate(v.3); Google Data Analytics Capstone: Complete a Case Study; Google Data Analytics; Introduction to Data Analysis Using Python; Share Data Through the Art of Visualization; Analyze Data to Answer Questions; Process Data from Dirty to Clean; Prepare Data for Exploration; Ask Questions to Make Data-Driven Decisions; Accelerate Your Job Search with AI; Google Cybersecurity; Put It to Work: Prepare for Cybersecurity Jobs; Imersão Front-End com IA; Início do projeto: Como começar um projeto bem-sucedido; Automate Cybersecurity Tasks with Python; Sound the Alarm: Detection and Response; Google AI Essentials; Stay Ahead of the AI Curve; Use AI Responsibly; Discover the Art of Prompting; Maximize Productivity With AI Tools; Introduction to AI; Fundamentos do gerenciamento de projetos; Google AI Essentials V1 - Badge; Google Prompting Essentials - Badge; Google Prompting Essentials; Use AI as a Creative or Expert Partner; Speed Up Data Analysis and Presentation Building; Design Prompts for Everyday Work Tasks; AWS Cloud Quest: Cloud Practitioner - Training Badge; Start Writing Prompts like a Pro; Assets, Threats, and Vulnerabilities; Foundations: Data, Data, Everywhere; Datadog Foundation; Tools of the Trade: Linux and SQL; Foundations of Cybersecurity; Play It Safe: Manage Security Risks; Connect and Protect: Networks and Network Security; Atividade - Plugin 24.1.",
      "Education details: https://pklavc.com/about/",
    ],
  },
];